plugins {
    id 'java-library'
    id 'maven-publish'
}

base {
    archivesName = 'volmlib-web'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release.set(17)
    options.compilerArgs.add('-parameters')
    options.encoding = 'UTF-8'
}

sourceSets {
    main {
        java {
            srcDirs = ['../shared/src/main/java']
            include('art/arcane/volmlib/util/web/MclogsClient.java')
        }
        resources {
            srcDirs = []
        }
    }
    test {
        java {
            srcDirs = []
        }
    }
}

dependencies {
    implementation('com.google.code.gson:gson:2.10.1')
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'volmlib-web'
            from(components.java)
        }
    }
}
